# Site settings
title: "Borch's Adventure"
email: canavate@protonmail.com
description: "Security and other stories"
baseurl: ""
url: "https://stoo0rmq.github.io/"
title_description: ""
title_image: "https://github.com/Stoo0rmq/Stoo0rmq.github.io/blob/master/images/bloodhound6.jpg"
google_analytics: ""
github_repository: https://github.com/Stoo0rmq/
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  
linkedin_link: 
google_plus_link: 
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: "Theme made by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
